

[markup]
  [markup.highlight]
  noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
    # unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
      block = true
      title = false
    [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

# hugo.toml
# Basic configuration


baseURL = 'https://infosec-mnit.github.io'
languageCode = "en-us"
title = 'Infosec MNIT'
paginage = 5
theme = "hugo-blog-awesome"

# Build options
buildDrafts = false
buildExpired = false
buildFuture = false

# Miscellaneous
enableGitInfo = true
enableEmoji = true

[markup]
	[markup.highlight]
	noClasses = false

	[markup.goldmark.renderer]
	# unsafe = true

	[markup.goldmark.parser]
		[markup.goldmark.parser.attribute]
		block = true
		title = false

	[markup.tableOfContents]
	startLevel = 2
	endLevel = 4
	ordered = false
