[[main]]
identifier = 'about'
name = 'About'
url = '/about'
weight = 1

[[main]]
identifier = 'resources'
name = 'Resources'
url = '/resources'
weight = 2

[[main]]
identifier = 'blog'
name = 'Blog'
url = '/blog'
weight = 3

[[main]]
identifier = 'members'
name = 'Members'
url = '/members'
weight = 4
